export type Region = "Peninsula" | "North Bay" | "South Bay" | "East Bay" | "Coast";

export type SiteType = "tent" | "rv" | "cabin" | "group";

export type BookingPlatform = "ReserveCalifornia" | "Recreation.gov" | "County" | "Private";

export interface Campsite {
  id: string;
  name: string;
  park: string;
  region: Region;
  lat: number;
  lng: number;
  siteTypes: SiteType[];
  dogFriendly: boolean;
  showers: boolean;
  reservable: boolean;
  priceRange: string;
  bookingUrl: string;
  bookingPlatform: BookingPlatform;
  driveNotes: string;
  description: string;
}

export const REGIONS: Region[] = ["Peninsula", "North Bay", "South Bay", "East Bay", "Coast"];

export const SITE_TYPES: { value: SiteType; label: string }[] = [
  { value: "tent", label: "Tent" },
  { value: "rv", label: "RV / Trailer" },
  { value: "cabin", label: "Cabin / Lodge" },
  { value: "group", label: "Group" },
];

const RC = "https://www.reservecalifornia.com/";
const RG = "https://www.recreation.gov/search?q=";

export const CAMPSITES: Campsite[] = [
  {
    id: "portola-redwoods",
    name: "Portola Redwoods",
    park: "Portola Redwoods State Park",
    region: "Peninsula",
    lat: 37.0536,
    lng: -122.1854,
    siteTypes: ["tent", "rv", "group"],
    dogFriendly: true,
    showers: true,
    reservable: true,
    priceRange: "$35–$65",
    bookingUrl: RC,
    bookingPlatform: "ReserveCalifornia",
    driveNotes: "~1 hr 15 min from SF via La Honda Rd",
    description: "Old-growth redwoods along Pescadero Creek with shaded, creekside sites. Classic Peninsula redwood camping.",
  },
  {
    id: "butano",
    name: "Butano",
    park: "Butano State Park",
    region: "Peninsula",
    lat: 37.2057,
    lng: -122.336,
    siteTypes: ["tent", "rv", "cabin"],
    dogFriendly: true,
    showers: true,
    reservable: true,
    priceRange: "$35–$75",
    bookingUrl: RC,
    bookingPlatform: "ReserveCalifornia",
    driveNotes: "~1 hr 30 min from SF via Pescadero",
    description: "Quiet redwood canyon campground with walk-in sites and drive-up loops, plus easy gorge trails.",
  },
  {
    id: "memorial-park",
    name: "Memorial Park",
    park: "Memorial County Park, San Mateo County",
    region: "Peninsula",
    lat: 37.2753,
    lng: -122.2983,
    siteTypes: ["tent", "rv", "group"],
    dogFriendly: true,
    showers: true,
    reservable: true,
    priceRange: "$35–$70",
    bookingUrl: "https://parks.smcgov.org/memorial-park",
    bookingPlatform: "County",
    driveNotes: "~1 hr from SF via Hwy 84",
    description: "Huge county park under second-growth redwoods in La Honda with tons of family sites and a swim area feel.",
  },
  {
    id: "half-moon-bay",
    name: "Half Moon Bay",
    park: "Half Moon Bay State Beach",
    region: "Coast",
    lat: 37.4691,
    lng: -122.4467,
    siteTypes: ["tent", "rv"],
    dogFriendly: false,
    showers: true,
    reservable: true,
    priceRange: "$35–$75",
    bookingUrl: RC,
    bookingPlatform: "ReserveCalifornia",
    driveNotes: "~40 min from SF via Hwy 92",
    description: "Beachfront bluffs campground steps from the sand. Windy, foggy, and unbeatable for ocean sunsets.",
  },
  {
    id: "sanborn",
    name: "Sanborn",
    park: "Sanborn County Park",
    region: "South Bay",
    lat: 37.2205,
    lng: -122.0683,
    siteTypes: ["tent", "rv", "cabin", "group"],
    dogFriendly: true,
    showers: true,
    reservable: true,
    priceRange: "$35–$80",
    bookingUrl: "https://parks.sccgov.org/sanborn-county-park",
    bookingPlatform: "County",
    driveNotes: "~1 hr from SF, 20 min from Saratoga",
    description: "Redwood-shaded Santa Cruz Mountain sites plus tent cabins, an easy escape above Silicon Valley.",
  },
  {
    id: "uvas-canyon",
    name: "Uvas Canyon",
    park: "Uvas Canyon County Park",
    region: "South Bay",
    lat: 37.0809,
    lng: -121.6911,
    siteTypes: ["tent", "rv", "group"],
    dogFriendly: true,
    showers: false,
    reservable: true,
    priceRange: "$35–$55",
    bookingUrl: "https://parks.sccgov.org/uvas-canyon-county-park",
    bookingPlatform: "County",
    driveNotes: "~1 hr 20 min from SF via Morgan Hill",
    description: "Small waterfall-canyon campground with lush swimming holes in spring and shady oak sites.",
  },
  {
    id: "henry-coe",
    name: "Henry W. Coe",
    park: "Henry W. Coe State Park",
    region: "South Bay",
    lat: 37.1859,
    lng: -121.5514,
    siteTypes: ["tent", "rv", "group"],
    dogFriendly: false,
    showers: false,
    reservable: false,
    priceRange: "$25–$35",
    bookingUrl: RC,
    bookingPlatform: "ReserveCalifornia",
    driveNotes: "~1 hr 30 min from SF via Morgan Hill",
    description: "Rugged backcountry-style camping at the edge of huge wilderness. First-come sites, big starry skies.",
  },
  {
    id: "castle-rock",
    name: "Castle Rock",
    park: "Castle Rock State Park",
    region: "South Bay",
    lat: 37.2312,
    lng: -122.0956,
    siteTypes: ["tent"],
    dogFriendly: false,
    showers: false,
    reservable: true,
    priceRange: "$35",
    bookingUrl: RC,
    bookingPlatform: "ReserveCalifornia",
    driveNotes: "~1 hr 10 min from SF via Skyline Blvd",
    description: "Climber's hideout among sandstone formations with hike-in vibe sites along the Skyline ridge.",
  },
  {
    id: "samuel-p-taylor",
    name: "Samuel P. Taylor",
    park: "Samuel P. Taylor State Park",
    region: "North Bay",
    lat: 38.0266,
    lng: -122.7289,
    siteTypes: ["tent", "rv", "cabin", "group"],
    dogFriendly: true,
    showers: true,
    reservable: true,
    priceRange: "$35–$85",
    bookingUrl: RC,
    bookingPlatform: "ReserveCalifornia",
    driveNotes: "~1 hr from SF via Sir Francis Drake Blvd",
    description: "Redwoods on Papermill Creek with bike-path access to Point Reyes. One of Marin's best family parks.",
  },
  {
    id: "china-camp",
    name: "China Camp",
    park: "China Camp State Park",
    region: "North Bay",
    lat: 38.009,
    lng: -122.48,
    siteTypes: ["tent", "rv", "group"],
    dogFriendly: true,
    showers: true,
    reservable: true,
    priceRange: "$35–$60",
    bookingUrl: RC,
    bookingPlatform: "ReserveCalifornia",
    driveNotes: "~45 min from SF via San Rafael",
    description: "Bay-front sites with mountain-bike trails out the tent flap and sunset views over San Pablo Bay.",
  },
  {
    id: "angel-island",
    name: "Angel Island",
    park: "Angel Island State Park",
    region: "North Bay",
    lat: 37.862,
    lng: -122.4325,
    siteTypes: ["tent", "group"],
    dogFriendly: false,
    showers: false,
    reservable: true,
    priceRange: "$30–$40",
    bookingUrl: RC,
    bookingPlatform: "ReserveCalifornia",
    driveNotes: "Ferry from SF or Tiburon, then hike in",
    description: "Boat-in-only island camping with 360-degree Bay views. Sites are hike-in, reservations essential.",
  },
  {
    id: "mt-tam",
    name: "Pantoll / Mt. Tam",
    park: "Mount Tamalpais State Park",
    region: "North Bay",
    lat: 37.9048,
    lng: -122.6078,
    siteTypes: ["tent", "rv", "group"],
    dogFriendly: false,
    showers: false,
    reservable: false,
    priceRange: "$25–$35",
    bookingUrl: RC,
    bookingPlatform: "ReserveCalifornia",
    driveNotes: "~1 hr from SF via Panoramic Hwy",
    description: "First-come redwood sites at Pantoll with trailheads to the summit and Steep Ravine in every direction.",
  },
  {
    id: "olema-ranch",
    name: "Olema Campground",
    park: "Olema Ranch (Point Reyes gateway)",
    region: "North Bay",
    lat: 38.0457,
    lng: -122.7865,
    siteTypes: ["tent", "rv", "cabin", "group"],
    dogFriendly: true,
    showers: true,
    reservable: true,
    priceRange: "$60–$120",
    bookingUrl: "https://www.olemacampground.net/",
    bookingPlatform: "Private",
    driveNotes: "~1 hr 15 min from SF via Point Reyes Station",
    description: "Private ranch campground minutes from Point Reyes trails, an easy backup when park sites sell out.",
  },
  {
    id: "point-reyes-coast",
    name: "Point Reyes Backcountry",
    park: "Point Reyes National Seashore",
    region: "North Bay",
    lat: 38.0178,
    lng: -122.8725,
    siteTypes: ["tent"],
    dogFriendly: false,
    showers: false,
    reservable: true,
    priceRange: "$20",
    bookingUrl: `${RG}Point%20Reyes`,
    bookingPlatform: "Recreation.gov",
    driveNotes: "~1 hr 30 min from SF + hike in",
    description: "Hike-in coastal camps (Coast, Glen, Sky, Wildcat) booked on Recreation.gov. Permits go fast in summer.",
  },
  {
    id: "bodega-dunes",
    name: "Bodega Dunes",
    park: "Sonoma Coast State Park",
    region: "North Bay",
    lat: 38.3249,
    lng: -123.0703,
    siteTypes: ["tent", "rv"],
    dogFriendly: true,
    showers: true,
    reservable: true,
    priceRange: "$35–$65",
    bookingUrl: RC,
    bookingPlatform: "ReserveCalifornia",
    driveNotes: "~1 hr 45 min from SF via Bodega Bay",
    description: "Dune-backed loops a short trail from a wide sandy beach. Great for groups and beach days.",
  },
  {
    id: "sugarloaf-ridge",
    name: "Sugarloaf Ridge",
    park: "Sugarloaf Ridge State Park",
    region: "North Bay",
    lat: 38.4603,
    lng: -122.5216,
    siteTypes: ["tent", "rv", "group"],
    dogFriendly: true,
    showers: true,
    reservable: true,
    priceRange: "$35–$60",
    bookingUrl: RC,
    bookingPlatform: "ReserveCalifornia",
    driveNotes: "~1 hr 30 min from SF via Kenwood",
    description: "Oak-woodland sites with waterfall hikes and an observatory, tucked into wine country hills.",
  },
  {
    id: "bothe-napa",
    name: "Bothe-Napa Valley",
    park: "Bothe-Napa Valley State Park",
    region: "North Bay",
    lat: 38.5536,
    lng: -122.5309,
    siteTypes: ["tent", "rv", "cabin", "group"],
    dogFriendly: true,
    showers: true,
    reservable: true,
    priceRange: "$35–$85",
    bookingUrl: RC,
    bookingPlatform: "ReserveCalifornia",
    driveNotes: "~1 hr 30 min from SF via St. Helena",
    description: "Redwood grove camping in the middle of Napa Valley with a pool (summer) and easy creek trails.",
  },
  {
    id: "kirby-cove",
    name: "Kirby Cove",
    park: "Golden Gate NRA — Kirby Cove",
    region: "North Bay",
    lat: 37.8273,
    lng: -122.4906,
    siteTypes: ["tent", "group"],
    dogFriendly: false,
    showers: false,
    reservable: true,
    priceRange: "$25–$40",
    bookingUrl: `${RG}Kirby%20Cove`,
    bookingPlatform: "Recreation.gov",
    driveNotes: "~30 min from SF, hike down from Conzelman Rd",
    description: "Five coveted sites under the Golden Gate with a rope swing and city views. Lottery-tough to book.",
  },
  {
    id: "rob-hill",
    name: "Rob Hill",
    park: "Presidio of San Francisco",
    region: "Peninsula",
    lat: 37.7862,
    lng: -122.4826,
    siteTypes: ["tent", "group"],
    dogFriendly: false,
    showers: false,
    reservable: true,
    priceRange: "$35–$130",
    bookingUrl: `${RG}Rob%20Hill%20Presidio`,
    bookingPlatform: "Recreation.gov",
    driveNotes: "In SF — bus or short drive to the Presidio",
    description: "SF's only campground: group and family sites in eucalyptus forest with the city at your doorstep.",
  },
  {
    id: "lawsons-landing",
    name: "Lawson's Landing",
    park: "Lawson's Landing, Dillon Beach (private)",
    region: "North Bay",
    lat: 38.2441,
    lng: -122.9647,
    siteTypes: ["tent", "rv"],
    dogFriendly: true,
    showers: true,
    reservable: true,
    priceRange: "$50–$100",
    bookingUrl: "https://www.lawsonslanding.com/",
    bookingPlatform: "Private",
    driveNotes: "~1 hr 45 min from SF via Tomales Bay",
    description: "Sprawling private dunes-and-beach camping with clamming, crabbing, and very dog-friendly vibes.",
  },
  {
    id: "mt-diablo",
    name: "Mt. Diablo",
    park: "Mount Diablo State Park",
    region: "East Bay",
    lat: 37.8801,
    lng: -121.9162,
    siteTypes: ["tent", "rv", "group"],
    dogFriendly: false,
    showers: false,
    reservable: true,
    priceRange: "$35–$50",
    bookingUrl: RC,
    bookingPlatform: "ReserveCalifornia",
    driveNotes: "~1 hr from SF via Walnut Creek",
    description: "Oak-savanna sites with huge views and wildflower springs. Juniper and Live Oak loops are the picks.",
  },
  {
    id: "del-valle",
    name: "Del Valle",
    park: "Del Valle Regional Park",
    region: "East Bay",
    lat: 37.5977,
    lng: -121.7067,
    siteTypes: ["tent", "rv", "group"],
    dogFriendly: true,
    showers: true,
    reservable: true,
    priceRange: "$25–$60",
    bookingUrl: "https://www.ebparks.org/parks/del-valle",
    bookingPlatform: "County",
    driveNotes: "~1 hr 20 min from SF via Livermore",
    description: "Lakeside East Bay camping with swim beach summers, boat ramps, and Ohlone Wilderness trailheads.",
  },
  {
    id: "chabot",
    name: "Anthony Chabot",
    park: "Anthony Chabot Regional Park",
    region: "East Bay",
    lat: 37.7699,
    lng: -122.1092,
    siteTypes: ["tent", "rv", "group"],
    dogFriendly: true,
    showers: false,
    reservable: true,
    priceRange: "$25–$50",
    bookingUrl: "https://www.ebparks.org/parks/anthony-chabot",
    bookingPlatform: "County",
    driveNotes: "~35 min from SF via Oakland hills",
    description: "Closest redwood-ish escape to the city: eucalyptus and bay forest sites above Lake Chabot.",
  },
  {
    id: "big-basin",
    name: "Big Basin (limited reopening)",
    park: "Big Basin Redwoods State Park",
    region: "Coast",
    lat: 37.1722,
    lng: -122.2229,
    siteTypes: ["tent"],
    dogFriendly: false,
    showers: false,
    reservable: true,
    priceRange: "$35–$50",
    bookingUrl: RC,
    bookingPlatform: "ReserveCalifornia",
    driveNotes: "~1 hr 45 min from SF via Boulder Creek",
    description: "California's oldest state park, partly reopened after the 2020 fire with limited reservable sites.",
  },
];
